---
- name: config ssh and user settings
  hosts: target_host
  become: yes
  vars:
    new_user: brickdev
    new_user_password: pass
    ssh_public_key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDDW1sg+ys6EEZd6ZzbDlrMMybOBUALEtERY2/ZKsvgbcAzTERxbtsqu+iNNDBo+sf3L3YuWkd8fLH4SJ3MQV42ySc6ml2tMT0G2r+QIWwFz+nPaD2DY8blgFpsa41TZxwKgLmqEtUVlps9Q6Un5KtJMjTl2MWYKswdxSqHw8em0DNigJolWfzsmoTvd1HXTYdj/PiJECW3nS38PFlL19Av6ipwrbxme2/VyvjolX5F3p/dgLkuUU7UMQ+tlx9gAlN0F/Tf6zMHSubIBC7lOf58zP+IlykdD4leVaNpFckk9hxnKCZpyM7jlwi2YSnYLAOh4v56NTq7c/yG2jX9+lSb"

  tasks:
    - name: create user
      user:
        name: "{{ new_user }}"
        password: "{{ new_user_password }}"
        shell: /bin/bash
        state: present

    - name: check user .ssh directory
      file:
        path: "/home/{{ new_user }}/.ssh"
        state: directory
        owner: "{{ new_user }}"
        group: "{{ new_user }}"
        mode: '0700'

    - name: add user ssh public key
      authorized_key:
        user: "{{ new_user }}"
        state: present
        key: "{{ ssh_public_key }}"

    - name: disable ssh root login 
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PermitRootLogin'
        line: 'PermitRootLogin no'
        state: present
      notify:
        - restart ssh

  handlers:
    - name: restart ssh
      service:
        name: ssh
        state: restarted