version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - AUTHOR=${AUTHOR}
      - UUID=${UUID}
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/hostname || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
    deploy:
      replicas: 3
