version: '3.8'

services:
  web:
    image: nodejs-web-app
    build: .
    deploy:
      replicas: 3
    ports:
      - "8000:8000"
    environment:
      - AUTHOR=brickdev
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/hostname"]
      interval: 10s
      timeout: 5s
      retries: 3
    entrypoint: [ "sh", "-c", "export UUID=$(hostname) && node app.js" ]
