version: '3.8'

services:
  web:
    build: .
    environment:
      - AUTHOR=devbrick
      - UUID=${UUID}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
