version: '3.8'

services:
  web:
    build: .
    environment:
      - AUTHOR=brickdev
      - UUID=${UUID}
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
      healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:8000/"]
        interval: 30s
        timeout: 10s
        retries: 3
